version: "3"
services:

  paylanes-api:
    container_name: 9to5-web
    image: "${APP_IMAGE}"
    env_file: .env
    ports:
      - '3000:3100'
    volumes:
      - "/opt/docker-mounts/9to5-web/public/uploads:/usr/src/app/public/uploads"
      - "/opt/docker-mounts/9to5-web/public/reportcsv:/usr/src/app/public/reportcsv"
      - "/opt/docker-mounts/9to5-web/airCaroDownload:/usr/src/app/airCaroDownload"
      - "/opt/docker-mounts/9to5-web:/usr/src/app/Templates"
      - "/opt/docker-mounts/9to5-web/public/manifest_files:/usr/src/app/public/manifest_files"
    restart: unless-stopped
